name: cache
description: >
  Utilities and classes around implementing or using a Cache
version: 0.1.0
authors:
  - Matan Lurey <matanl@google.com>
homepage: https://github.com/matanlurey/cache.dart

environment:
  sdk: ">=1.8.0 <2.0.0"

dev_dependencies:
  test:
